### ISSUE TITLE
apache2 Chef-13

### ISSUE THREAD

**Issue by damacus** [sous-chefs/apache2#468]

**Comment by damacus** [comment]
```
Deprecated features used!
         Property `sensitive` of resource `apt_repository` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
           - /tmp/kitchen/cache/cookbooks/apt/resources/repository.rb:54:in `class_from_file'
          See https://docs.chef.io/deprecations_property_name_collision.html for further details.
         Cloning resource attributes for template[/etc/httpd/sites-available/secure.conf] from prior resource
       Previous template[/etc/httpd/sites-available/secure.conf]: /tmp/kitchen/cache/cookbooks/apache2/definitions/web_app.rb:28:in `block in from_file'
       Current  template[/etc/httpd/sites-available/secure.conf]: /tmp/kitchen/cache/cookbooks/apache2/definitions/web_app.rb:28:in `block in from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/apache2/definitions/web_app.rb:28:in `block in from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
         Cloning resource attributes for execute[a2ensite secure.conf] from prior resource
       Previous execute[a2ensite secure.conf]: /tmp/kitchen/cache/cookbooks/apache2/definitions/apache_site.rb:25:in `block in from_file'
       Current  execute[a2ensite secure.conf]: /tmp/kitchen/cache/cookbooks/apache2/definitions/apache_site.rb:25:in `block in from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/apache2/definitions/apache_site.rb:25:in `block in from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
         Cloning resource attributes for script[add-credentials] from prior resource
       Previous script[add-credentials]: /tmp/kitchen/cache/cookbooks/apache2_test/recipes/mod_authz_groupfile.rb:31:in `from_file'
       Current  script[add-credentials]: /tmp/kitchen/cache/cookbooks/apache2_test/recipes/mod_authz_user.rb:29:in `from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/apache2_test/recipes/mod_authz_user.rb:29:in `from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
         Cloning resource attributes for template[/etc/httpd/mods-available/status.conf] from prior resource
       Previous template[/etc/httpd/mods-available/status.conf]: /tmp/kitchen/cache/cookbooks/apache2/definitions/apache_mod.rb:23:in `block in from_file'
       Current  template[/etc/httpd/mods-available/status.conf]: /tmp/kitchen/cache/cookbooks/apache2_test/recipes/mod_status_remote.rb:22:in `from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/apache2_test/recipes/mod_status_remote.rb:22:in `from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
```

**Comment by grv87** [comment]
```
[2017-06-17T19:52:10+00:00] WARN: Cloning resource attributes for file[/etc/apache2/mods-available/headers.load] from prior resourceer
Previous file[/etc/apache2/mods-available/headers.load]: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/apache2/definitions/apache_module.rb:29:in `block in from_file'
Current  file[/etc/apache2/mods-available/headers.load]: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/apache2/definitions/apache_module.rb:29:in `block in from_file' (CHEF-3694)/tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/apache2/definitions/apache_module.rb:29:in `block in from_file'.
Please see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
[2017-06-17T19:52:10+00:00] WARN: Cloning resource attributes for execute[a2enmod headers] from prior resource
Previous execute[a2enmod headers]: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/apache2/definitions/apache_module.rb:35:in `block in from_file'
Current  execute[a2enmod headers]: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/apache2/definitions/apache_module.rb:35:in `block in from_file' (CHEF-3694)/tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/apache2/definitions/apache_module.rb:35:in `block in from_file'.
Please see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
```

**Comment by tas50** [comment]
All testing is running in 13 and we're not seeing issues now. I'm going to close this out
