### ISSUE TITLE
can't modify frozen #<Class:Chef::Resource::Template>

### ISSUE THREAD

**Issue by pariminaresh** [sous-chefs/apache2#476]
### Cookbook version
"version":"3.2.2"

### Chef-client version
Chef Client, version 13.0.113

### Platform Details
centos-7.2

### Scenario:
[What you are trying to achieve and you can't?]
Including apache2 default recipe in my cookbook

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
 - Create a cookbook wrapper_apache
 - Add the dependency of 'apache2' in 'wrapper_apache' cookbook metadata.rb
 - Include_recipe 'apache2::default' in wrapper_apache::default recipe
 - Test using kitchen converge

### Expected Result:
 - I expect the apache2::default recipe to converge successfully

### Actual Result:
 - RuntimeError
       ------------
       can't modify frozen #<Class:Chef::Resource::Template>

Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb:69:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb:60:in `each'
         /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb:60:in `from_file'
         /tmp/kitchen/cache/cookbooks/wrapper_apache/recipes/default.rb:2:in `from_file'

**Comment by svanzoest** [comment]
Thanks for the report.
I am trying to reproduce it using centos 7.3 from our test kitchen configuration and I am not able to reproduce. Are you interacting with that template in the wrapper by any chance?

**Comment by pariminaresh** [comment]
Thanks. I'm not doing any template interactions in the wrapper though I missed a point here that my cookbook depends on other cookbooks too. With trial and error, I found that the combination of apache2 with concat cookbook is causing that issue.

In my cookbook metadata.rb I have lots other dependencies including below:
   depends 'apache2', '~>3.2.2' 
   depends 'concat'

**Comment by svanzoest** [comment]
Are you doing anything with the concat cookbook that would alter any of the apache2 templates? That could likely would be the code to inspect a little closer.
