### ISSUE TITLE
mod_ldap errors

### ISSUE THREAD

**Issue by mtory** [sous-chefs/apache2#501]
### Cookbook version
5.0.0

### Chef-client version
12, 13

### Platform Details
Ubuntu 14.04.3, 14.04.5 OpenStack / kitchen

### Scenario:
Simply running chef-client using apache2 as an upstream cookbook.

### Steps to Reproduce:
run chef-client 

### Expected Result:
Expect to run and set up ldap module for apache

### Actual Result:
```
Recipe: apache2::mod_ldap
  * apt_package[mod_ldap] action install
    * No candidate version available for mod_ldap
    ================================================================================
    Error executing action `install` on resource 'apt_package[mod_ldap]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for mod_ldap

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/apache2/recipes/mod_ldap.rb

     20: package 'mod_ldap'
     21:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/apache2/recipes/mod_ldap.rb:20:in `from_file'

    apt_package("mod_ldap") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "mod_ldap"
      declared_type :package
      cookbook_name "apache2"
      recipe_name "mod_ldap"
    end
```

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
