### ISSUE TITLE
Chefspec version 7.3.4 causes failures due to definitions being deprecated

### ISSUE THREAD

**Issue by lordkage** [sous-chefs/apache2#588]
### Cookbook version
`5.2.1`

### Chef-client version
chefdk `3.6.57`
chef `14.8.12`
chefspec `7.3.4`

### Platform Details
Development OS: `Mac OS 13`
Target OS: `CentOS 7`

### Scenario:
Including `apache2::default` causes unit testing to fail. Period. Integration and deployment still appear to be unaffected.

### Steps to Reproduce:
Include the `apache2::default` on recipe that has a spec file, run chefspec against it.

### Expected Result:
Unit testing to proceed as expected.

### Actual Result:
```
================================================================================
Recipe Compile Error in /var/folders/7x/jmvtwc388xj8xw001s76t54h0000gn/T/chefspec20190105-43843-1v7wnnefile_cache_path/cookbooks/mentat/recipes/apache.rb
================================================================================

NoMethodError
-------------
undefined method `params' for nil:NilClass

Cookbook Trace:
---------------
  /var/folders/7x/jmvtwc388xj8xw001s76t54h0000gn/T/chefspec20190105-43843-1v7wnnefile_cache_path/cookbooks/apache2/recipes/default.rb:179:in `block in from_file'
  /var/folders/7x/jmvtwc388xj8xw001s76t54h0000gn/T/chefspec20190105-43843-1v7wnnefile_cache_path/cookbooks/apache2/recipes/default.rb:178:in `each'
  /var/folders/7x/jmvtwc388xj8xw001s76t54h0000gn/T/chefspec20190105-43843-1v7wnnefile_cache_path/cookbooks/apache2/recipes/default.rb:178:in `from_file'
  /var/folders/7x/jmvtwc388xj8xw001s76t54h0000gn/T/chefspec20190105-43843-1v7wnnefile_cache_path/cookbooks/mentat/recipes/apache.rb:7:in `from_file'

Relevant File Content:
----------------------
/var/folders/7x/jmvtwc388xj8xw001s76t54h0000gn/T/chefspec20190105-43843-1v7wnnefile_cache_path/cookbooks/apache2/recipes/default.rb:

172:      apache_binary: apache_binary,
173:      apache_dir: apache_dir
174:    )
175:    notifies :reload, 'service[apache2]', :delayed
176:  end
177:
178:  %w(security charset).each do |conf|
179>>   apache_conf conf do
180:      enable true
181:    end
182:  end
183:
184:  template 'ports.conf' do
185:    path "#{apache_dir}/ports.conf"
186:    source 'ports.conf.erb'
187:    mode '0644'
188:    notifies :restart, 'service[apache2]', :delayed

System Info:
------------
chef_version=14.8.12
platform=centos
platform_version=7.5.1804
ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin16]
program_name=/opt/chefdk/embedded/bin/rspec
executable=/opt/chefdk/embedded/bin/rspec
```

Related Chefspec issue: https://github.com/chefspec/chefspec/issues/926

**Comment by damacus** [comment]
Yeah, I really hear you on this one. It's been a thorn on my side for 6+ months, rewriting this and getting some of the magic better documented. 
 
This milestone is what's left to be written https://github.com/sous-chefs/apache2/milestone/8

I'm currently working on the ssl & website resource as we speak. So if you're OK with no mod_php support, I'm inclined the cut v6 at that point

**Comment by lordkage** [comment]
Unfortunately, I am leveraging `mod_php` and `mod_ssl` as part of the cookbook I am currently building. I have set my chefdk to and older version for the moment, until the version is available.
